version: '3.1'

services:
  url_shortener:
    container_name: url_shortener
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      TRANSPORT_MODE: ${TRANSPORT_MODE}
      STORAGE_TYPE: ${STORAGE_TYPE}
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - ps
  
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - ps

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ps

networks:
  ps: 