server:
  http_port: "8000"
  grpc_port: "8001"

database:
  type: "postgres"
  postgres:
    user: "postgres"
    password: "postgres"
    dbname: "postgres"
    host: "postgres"
    port: "5432"
  redis:
    password: ""
    host: "redis"
    port: "6379" 